package bean;

// Generated 17/06/2015 01:53:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private long idUsuario;
	private String usuario;
	private String contrasenia;
	private Long sesion;
	private Long estado;
	private Long intentos;
	private Date ultimoIntento;

	public Usuario() {
	}

	public Usuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Usuario(long idUsuario, String usuario, String contrasenia,
			Long sesion, Long estado, Long intentos, Date ultimoIntento) {
		this.idUsuario = idUsuario;
		this.usuario = usuario;
		this.contrasenia = contrasenia;
		this.sesion = sesion;
		this.estado = estado;
		this.intentos = intentos;
		this.ultimoIntento = ultimoIntento;
	}

	public long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public Long getSesion() {
		return this.sesion;
	}

	public void setSesion(Long sesion) {
		this.sesion = sesion;
	}

	public Long getEstado() {
		return this.estado;
	}

	public void setEstado(Long estado) {
		this.estado = estado;
	}

	public Long getIntentos() {
		return this.intentos;
	}

	public void setIntentos(Long intentos) {
		this.intentos = intentos;
	}

	public Date getUltimoIntento() {
		return this.ultimoIntento;
	}

	public void setUltimoIntento(Date ultimoIntento) {
		this.ultimoIntento = ultimoIntento;
	}

}
